export default defineI18nLocale(() => ({
  legal: {
    contents: 'Contents',
    contentsLabel: 'Legal document sections',
    questionsEyebrow: 'SUPPORT',
    questionsTitle: 'Need help with an order or your account?',
    questionsCopy: 'Our support team can help with account, order, payment, delivery and privacy questions through your Pelissa account.',
    contactSupport: 'Contact support',
    privacy: {
      seoTitle: 'Privacy Policy | PELISSA°',
      seoDescription: 'Learn how PELISSA collects, uses and protects information when you browse and shop with us.',
      eyebrow: 'LEGAL INFORMATION',
      title: 'Privacy Policy',
      intro: 'This Privacy Policy explains how information is handled when you browse, create an account, shop or contact support through the PELISSA storefront.',
      updated: 'Last updated · 19 August 2026',
      notice: 'This policy covers the PELISSA customer storefront, account services, checkout and support tools. Payment and delivery providers may give you their own privacy notices, which apply to the services they provide.',
      sections: [
        {
          title: 'Scope and updates',
          paragraphs: [
            'This policy describes how PELISSA handles personal information connected with our customer-facing storefront and related services. It applies whether you visit the site, use an account, make a purchase or contact our support team.',
            'We may revise this policy when our services, providers or legal obligations change. The current version will be posted on this page with an updated date. Where a change is material, we may also provide notice through the storefront or by email.',
          ],
        },
        {
          title: 'Information you provide',
          paragraphs: [
            'You may provide information when you create an account, place an order, save an address, update your profile, contact support or choose to receive marketing messages. This can include your name, email address, username, phone number, shipping and billing details, order history and the content of your messages.',
            'Please make sure information you submit is accurate and current. If you give us information about another person, you should have permission to do so.',
          ],
        },
        {
          title: 'Information collected through use',
          paragraphs: [
            'When you use the storefront, we may collect information generated by that use, such as products viewed, cart contents, language and currency preferences, device and browser details, approximate region, pages visited and records needed to diagnose errors or protect the service.',
            'Some of this information is collected through cookies, browser storage and similar technologies. It helps the storefront remember essential choices and operate reliably.',
          ],
        },
        {
          title: 'How we use information',
          bullets: [
            'Provide the storefront, account, cart, checkout, order, delivery and support features you request.',
            'Process and administer orders, payments, refunds, customer-service requests and necessary account communications.',
            'Authenticate accounts, send verification codes and protect customers and the storefront from fraud, abuse and unauthorized access.',
            'Understand and improve product discovery, storefront performance and support quality, including through aggregated analysis.',
            'Send marketing messages only where you have made that choice; you can unsubscribe or withdraw consent at any time.',
          ],
        },
        {
          title: 'Cookies and preference storage',
          paragraphs: [
            'We use essential cookies and local storage to maintain a session, remember your locale and currency preferences, protect forms and keep your cart available. Where optional analytics are used, they help us understand how the storefront is performing and where it can be improved.',
            'You can manage cookies through your browser settings. Blocking essential storage can prevent parts of the storefront, including sign-in, cart and checkout, from working as expected.',
          ],
        },
        {
          title: 'Payments and service providers',
          paragraphs: [
            'Payments are processed by Stripe or another provider shown during checkout. PELISSA does not store complete card numbers or card security codes. The payment provider processes payment details under its own terms and privacy notice and may return a payment status, transaction identifier or receipt information to us.',
            'We may use carefully selected providers for services such as hosting, email delivery, authentication, customer support, analytics and shipping. They process information only as needed to provide their services to us and under applicable confidentiality and security obligations.',
          ],
        },
        {
          title: 'Sharing and international processing',
          paragraphs: [
            'We share information with service providers when it is needed to run the storefront and fulfill your order, and with payment, delivery or support partners involved in the service you request. We may also disclose information where required by law or when reasonably necessary to protect customers, the public or our rights.',
            'Our providers and systems may process information in countries other than the one where you live. When this happens, we use safeguards appropriate to the transfer and the service involved where required by applicable law.',
          ],
        },
        {
          title: 'Retention and security',
          paragraphs: [
            'We retain information only for as long as reasonably needed to provide services, complete transactions, meet legal and accounting requirements, resolve disputes and enforce agreements. Retention periods vary by the type of information and why it was collected.',
            'We use measures such as access controls, encryption in transit and operational safeguards designed to protect information. No online service can guarantee absolute security, so please use a unique password and contact support promptly if you suspect unauthorized account activity.',
          ],
        },
        {
          title: 'Your rights and choices',
          paragraphs: [
            'Depending on where you live, you may have rights to access, correct, delete, restrict or receive a copy of personal information, and to object to certain processing. You can update some profile information in your account and unsubscribe from marketing messages directly.',
            'For other privacy requests, please contact support. We may need to verify your identity before responding, and we will explain if an applicable law allows or requires us to limit a request.',
          ],
        },
        {
          title: 'Children',
          paragraphs: [
            'The storefront is not intended for children who cannot lawfully consent to online services in their location. If you believe a child has provided us with personal information, please contact support so we can review the matter and take appropriate action.',
          ],
        },
        {
          title: 'Contact us',
          paragraphs: [
            'If you have a question about this policy, your information or a privacy request, submit it through the PELISSA support area in your account. We may use account information to verify and respond to your request securely.',
          ],
        },
      ],
    },
    terms: {
      seoTitle: 'Terms of Service | PELISSA°',
      seoDescription: 'Read the terms that apply when you use the PELISSA storefront, account, checkout and support services.',
      eyebrow: 'LEGAL INFORMATION',
      title: 'Terms of Service',
      intro: 'These Terms of Service explain the rules for using the PELISSA storefront and how accounts, orders, payment, delivery and customer support are handled.',
      updated: 'Last updated · 19 August 2026',
      notice: 'By browsing the storefront, creating an account or placing an order, you agree to these terms. If you do not agree, please do not use the storefront or its related services.',
      sections: [
        {
          title: 'Agreement and scope',
          paragraphs: [
            'These terms apply to your use of the PELISSA customer storefront, including browsing, account services, checkout, orders and support. Additional notices displayed with a product, checkout flow or order may also apply to that purchase or feature.',
            'If a mandatory consumer-protection law in your location gives you rights that differ from these terms, that law continues to apply to the extent required.',
          ],
        },
        {
          title: 'Eligibility and account security',
          paragraphs: [
            'You may use PELISSA for personal, lawful shopping and account purposes. You must provide accurate information and keep it up to date. If you create an account, keep your password and verification codes confidential and notify support if you suspect unauthorized activity.',
            'You are responsible for activity carried out through your account unless it resulted from our failure to use reasonable security measures. We may ask you to verify information before completing an account or order-related request.',
          ],
        },
        {
          title: 'Products, pricing and availability',
          paragraphs: [
            'We work to describe products, colors, sizing, stock status and prices accurately. Device settings can affect how colors and images appear. Products may be limited, discontinued or unavailable, and we may correct a clear listing error or limit quantities before accepting an order.',
            'Unless checkout clearly states otherwise, product prices and order totals are shown in USD. Shipping, taxes, customs charges and other disclosed amounts may be added or handled as shown during checkout.',
          ],
        },
        {
          title: 'Orders and acceptance',
          paragraphs: [
            'Submitting an order is an offer to buy the selected products. We accept an order when we confirm it or begin fulfillment. We may decline or cancel an order for reasons such as inventory, a pricing error, payment failure, address issues, suspected fraud or legal requirements.',
            'If we cancel an order after payment has been taken, we will return the amount paid when required. Order confirmation does not guarantee that every item will remain available until fulfillment.',
          ],
        },
        {
          title: 'Payment',
          paragraphs: [
            'Payment is processed by Stripe or another provider displayed at checkout. By submitting an order, you authorize us and the payment provider to charge the selected method for the confirmed total, including applicable shipping, tax and other disclosed charges.',
            'You must be authorized to use the payment method you select. Payment providers may apply their own terms, verification steps or fraud checks, and an order cannot be completed if payment authorization is not obtained.',
          ],
        },
        {
          title: 'Shipping, customs and delivery',
          paragraphs: [
            'Available delivery methods, charges and estimated times are shown during checkout or in your order details. Delivery dates are estimates, not guarantees. Carrier delays, customs processing, weather and events outside our reasonable control may affect timing.',
            'You are responsible for providing a complete and accurate delivery address. Where applicable, import duties, taxes or customs requirements may be your responsibility as shown during checkout or required by the destination country.',
          ],
        },
        {
          title: 'Cancellations, returns and refunds',
          paragraphs: [
            'Cancellation, return and refund options are handled under the policy displayed with your order or in the support flow. Please review the information provided for your purchase before submitting a request.',
            'When a refund is approved, it is generally sent to the original payment method. The time it takes to appear can depend on the payment provider and your financial institution.',
          ],
        },
        {
          title: 'Intellectual property',
          paragraphs: [
            'The PELISSA name, product photography, copy, logos, designs, software and other storefront materials belong to PELISSA or its licensors. You may use them only as needed to browse and shop through the storefront.',
            'You may not copy, modify, distribute, publicly display or commercially exploit storefront materials without prior permission, except where applicable law permits it.',
          ],
        },
        {
          title: 'Acceptable use',
          bullets: [
            'Do not interfere with the storefront, bypass security controls or attempt to gain unauthorized access to an account, system or data.',
            'Do not scrape or collect storefront content at scale, introduce harmful code or use automated activity that disrupts the service.',
            'Do not impersonate another person, provide deceptive information or use the service to violate a law or another person’s rights.',
          ],
        },
        {
          title: 'User content and feedback',
          paragraphs: [
            'If you submit reviews, messages, suggestions or other content, you keep ownership of that content. You grant PELISSA a non-exclusive, worldwide, royalty-free license to host, display, adapt and use it as needed to operate, promote and improve the service.',
            'Do not submit content that is unlawful, misleading, abusive, infringing or confidential. We may remove content or restrict access when reasonably necessary to protect customers, the service or our legal rights.',
          ],
        },
        {
          title: 'Third-party services',
          paragraphs: [
            'The storefront may rely on third-party services such as payment processors, carriers and analytics providers. Their services are governed by their own terms and privacy notices. We are not responsible for third-party services outside our reasonable control.',
          ],
        },
        {
          title: 'Disclaimers, liability and changes',
          paragraphs: [
            'The storefront is provided on an availability basis. To the extent permitted by law, we disclaim implied warranties and are not responsible for indirect, incidental, special or consequential loss arising from use of the service, third-party services or events outside our reasonable control.',
            'Nothing in these terms excludes rights or remedies that cannot legally be excluded, or limits liability for fraud, willful misconduct or another liability that applicable law does not allow us to limit. We may update these terms as the storefront changes. The revised version is effective when posted unless a later date is stated; continuing to use the service after that date means you accept the revised terms.',
          ],
        },
        {
          title: 'Contact us',
          paragraphs: [
            'Questions about an account, order or these terms can be submitted through the PELISSA support area. We may use information associated with your account to verify and respond to your request.',
          ],
        },
      ],
    },
  },
}))
